// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "74f47dce90760103ec4533b3d647781cef8831fb2435d554ea282bdad6e07c78")
