// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "0bc7ff5950dbc6da917d15a117fee08b59e1bce787085c94a6a5669b3aec627f")
