// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "6b2b97cd66b5e194a80bcfa4be151dd788042491008911e9954a72e368b54810")
